version: '2.1'
services:
  hmi:
    build: https://github.com/sintax1/docker-mango-hmi.git
    image: "sintax1/mango-hmi"
    ports:
     - "8080:8080"
    networks:
     - scada-ot-1
    links:
      - plc1
    volumes:
      - /var/run/dbus:/var/run/dbus
    hostname: hmi

  scadasim:
    build: https://github.com/sintax1/docker-scadasim.git
    image: "sintax1/modbus-plc-simulator-master"
    networks:
      - scada-ot-1
    volumes:
      - ./scadasim_configs:/scadasim_configs/
      - /var/run/dbus:/var/run/dbus
    entrypoint: ["python", "-i", "run.py", "-c", "/scadasim_configs/scadasim_config.yml", "-d"]
    hostname: scadasim
    tty: true
    stdin_open: true

  plc1:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-1"
    networks:
      - scada-ot-1
    volumes:
      - /var/run/dbus:/var/run/dbus
    depends_on:
      - "scadasim"
    hostname: plc1

  plc2:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-2"
    networks:
      - scada-ot-1
    volumes:
      - /var/run/dbus:/var/run/dbus
    depends_on:
      - "scadasim"
    hostname: plc2

  plc3:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-3"
    networks:
      - scada-ot-1
    volumes:
      - /var/run/dbus:/var/run/dbus
    depends_on:
      - "scadasim"
    hostname: plc3

  chlorinatorplc:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-4"
    networks:
      - scada-ot-1
    volumes:
      - /var/run/dbus:/var/run/dbus
    depends_on:
      - "scadasim"
    hostname: chlorinatorplc

  attack:
    build: https://github.com/sintax1/docker-scadasim-attack.git
    image: "sintax1/scadasim-attack"
    networks:
      - scada-ot-1
    hostname: attack
    tty: true
    stdin_open: true

networks:
  scada-ot-1:
