version: '2.1'
services:
  hmi:
    build: https://github.com/sintax1/docker-mango-hmi.git
    image: "sintax1/mango-hmi"
    ports:
     - "8080:8080"
    networks:
     - scada-ot-1
    links:
      - plc1

  plc1:
    build: https://github.com/sintax1/docker-scadasim.git
    image: "sintax1/modbus-plc-simulator-master"
    networks:
      - scada-ot-1

  plc1:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-1"
    networks:
      - scada-ot-1

  plc2:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-2"
    networks:
      - scada-ot-1

  plc3:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-3"
    networks:
      - scada-ot-1

  chlorinatorplc:
    build: https://github.com/sintax1/docker-scadasim-plc.git
    image: "sintax1/modbus-plc-simulator-4"
    networks:
      - scada-ot-1

networks:
  scada-ot-1:
